config/routes.rb
Rails.application.routes.draw do

  # get 'daily_sales/index'

  # get 'order_lines/index'
  get 'orders/summary'
  get '/daily_sales' => 'orders#daily_sales', :as => :daily_sales
  get '/cashiers/ranking'
  get '/guests/products' => 'guests#products'
  get '/guests/meat' => 'guests#meat'
  get '/guests/produce' => 'guests#produce'
  get '/guests/cannedgoods' => 'guests#canned_goods'
  get '/guests/sweets' => 'guests#sweets'
  get '/guests/hygiene' => 'guests#hygiene'
  get 'cashiers/daily_sales' => 'cashiers#daily_sales'

  # get 'cashiers/index'

  devise_for :cashiers
  # , :controller => {:registrations => 'cashiers/registrations'}
  devise_for :admins
 
  root 'home#index'
  # devise_scope :admin do
  resources :home, :cashiers, :products, :orders, :order_lines, :daily_sales
  # map.orders '/daily_sales', :controller => 'order', :action => 'dailysales'
  # resources :orders go 
  #   get 'summary', :on => :collection
  # end
  # resources :orders, :path_prefix => ':cashiers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/guests_controller.rb
class GuestsController < ApplicationController
  
  def index
    render :layout => false
  end

  def show
    @products = Product.all
  end
  
  def products 
    @products = Product.all
    render :layout => false
  end
  
  def meat
    @active = Product.where(:status => true)
    @products = @active.where(:tag => "Meat")
    if @products.size == 0
      redirect_to guests_products_path, :alert => "No products available in this category."
    else
      render :meat, :layout => false
    end
  end
  
  def produce
    @active = Product.where(:status => true)
    @products = @active.where(:tag => "Produce")
    if @products.size == 0
      redirect_to guests_products_path, :alert => "No products available in this category."
    else
      render :produce, :layout => false
    end
  end
  
  def canned_goods
    @active = Product.where(:status => true)
    @products = @active.where(:tag => "Canned Goods")
    if @products.size == 0
      redirect_to guests_products_path, :alert => "No products available in this category."
    else
      render :cannedgoods, :layout => false
    end
  end
  
  def sweets
    @active = Product.where(:status => true)
    @products = @active.where(:tag => "Sweets")
    if @products.size == 0
      redirect_to guests_products_path, :alert => "No products available in this category."
    else
      render :sweets, :layout => false
    end
  end
  
  def hygiene
    @active = Product.where(:status => true)
    @products = @active.where(:tag => "Hygiene")
    if @products.size == 0
      redirect_to guests_products_path, :alert => "No products available in this category."
    else
      render :hygiene, :layout => false
    end
    
    # render :layout => false
  end
end

app/views/guests/cannedgoods.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MIS21 POS System</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'style', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <style>
      body{
      	height:100%;
      	width:100%;
      	margin: 0 0 0 0;
      	padding:20px 10px 10px 10px;
      	font-family: "Century Gothic";
      	background-image: url(http://cdn.wonderfulengineering.com/wp-content/uploads/2013/12/metal-wallpapers-2.jpg);
      	color: white;
      }
      
      div{
      	height:100%;
      	font-family: "Century Gothic";
      	color: white;
      }
      
      h1{
      	font-size: 7em;
      	color: white;
      }
      
      u{
      	border-bottom: 3px solid white;
      	text-decoration: none;
      	padding: 0 50px 10px;
      }
      
      .buttonBack{
          display: inline-block;
          border-radius: 10px;
          background-color: #B0C4DE;
          border: 3px solid #f2f2f2;
          color: black;
          text-align: center;
          font-size: 14px;
          padding: 10px;
          width: 100px;
          transition: all 0.5s;
          cursor: pointer;
          margin: 5px;
      }
    </style>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="navbar-header">
        <a class="navbar-brand" href="/guests/products"><strong>POS System</strong></a>
      </div>
      
      <p class="navbar-text pull-left">
        <%= link_to "View All Products", guests_products_path, :class => 'navbar-link'  %>
      </p>
      <p class="navbar-text pull-right">
        Viewing as Guest. |
        <%= link_to "End Session", root_path %>
      </p>
    </nav>
    
    <!--%= stylesheet_link_tag    'style', 'data-turbolinks-track': 'reload' %>-->

    <h1 align="right"><u>Canned Goods</u></h1>
    
    <br>
    <br>
    <br>
    
    <table class="table table-striped">
        <thead>
            <th style="text-align: center">#</th>
            <th style="text-align: center">Product Name</th>
            <th>Price</th>
        </thead>
        <tbody>
            <% @products.each do |this_product| %>
            <tr>
                <td style="text-align: center">
                    <%= @products.index(this_product) + 1 %>
                </td>
                <td style="text-align: center">
                    <%= this_product.name %>
                </td>
                <td>
                    <%= "%.2f" % this_product.price %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
    
    <%= link_to 'Back', home_index_path, class: "btn btn-warning buttonBack" %>
  </body>
</html>

app/views/guests/hygiene.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MIS21 POS System</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'style', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <style>
      body{
      	height:100%;
      	width:100%;
      	margin: 0 0 0 0;
      	padding:20px 10px 10px 10px;
      	font-family: "Century Gothic";
      	background-image: url(http://cdn.wonderfulengineering.com/wp-content/uploads/2013/12/metal-wallpapers-2.jpg);
      	color: white;
      }
      
      div{
      	height:100%;
      	font-family: "Century Gothic";
      	color: white;
      }
      
      h1{
      	font-size: 7em;
      	color: white;
      }
      
      u{
      	border-bottom: 3px solid white;
      	text-decoration: none;
      	padding: 0 50px 10px;
      }
      
      .buttonBack{
          display: inline-block;
          border-radius: 10px;
          background-color: #B0C4DE;
          border: 3px solid #f2f2f2;
          color: black;
          text-align: center;
          font-size: 14px;
          padding: 10px;
          width: 100px;
          transition: all 0.5s;
          cursor: pointer;
          margin: 5px;
      }
    </style>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="navbar-header">
        <a class="navbar-brand" href="/guests/products"><strong>POS System</strong></a>
      </div>
      
      <p class="navbar-text pull-left">
        <%= link_to "View All Products", guests_products_path, :class => 'navbar-link'  %>
      </p>
      <p class="navbar-text pull-right">
        Viewing as Guest. |
        <%= link_to "End Session", root_path %>
      </p>
    </nav>
    
    <!--%= stylesheet_link_tag    'style', 'data-turbolinks-track': 'reload' %>-->

    <h1 align="right"><u>Hygiene</u></h1>
    
    <br>
    <br>
    <br>
    
    <table class="table table-striped">
        <thead>
            <th style="text-align: center">#</th>
            <th style="text-align: center">Product Name</th>
            <th>Price</th>
        </thead>
        <tbody>
            <% @products.each do |this_product| %>
            <tr>
                <td style="text-align: center">
                    <%= @products.index(this_product) + 1 %>
                </td>
                <td style="text-align: center">
                    <%= this_product.name %>
                </td>
                <td>
                    <%= "%.2f" % this_product.price %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
    
    <%= link_to 'Back', home_index_path, class: "btn btn-warning buttonBack" %>
  </body>
</html>

app/views/guests/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MIS21 POS System</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'style' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="navbar-header">
        <a class="navbar-brand" href="/home"><strong>POS System</strong></a>
      </div>
      
      <p class="navbar-text pull-left">
        <%= link_to "View Products", guests_products_path, :class => 'navbar-link'  %>
      </p>
      <p class="navbar-text pull-right">
        Viewing as Guest. |
        <%= link_to "End Session", root_path %>
      </p>
    </nav>
  </body>
</html>

app/views/guests/meat.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MIS21 POS System</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'style', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <style>
      body{
      	height:100%;
      	width:100%;
      	margin: 0 0 0 0;
      	padding:20px 10px 10px 10px;
      	font-family: "Century Gothic";
      	background-image: url(http://cdn.wonderfulengineering.com/wp-content/uploads/2013/12/metal-wallpapers-2.jpg);
      	color: white;
      }
      
      div{
      	height:100%;
      	font-family: "Century Gothic";
      	color: white;
      }
      
      h1{
      	font-size: 7em;
      	color: white;
      }
      
      u{
      	border-bottom: 3px solid white;
      	text-decoration: none;
      	padding: 0 50px 10px;
      }
      
      .buttonBack{
          display: inline-block;
          border-radius: 10px;
          background-color: #B0C4DE;
          border: 3px solid #f2f2f2;
          color: black;
          text-align: center;
          font-size: 14px;
          padding: 10px;
          width: 100px;
          transition: all 0.5s;
          cursor: pointer;
          margin: 5px;
      }
    </style>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="navbar-header">
        <a class="navbar-brand" href="/guests/products"><strong>POS System</strong></a>
      </div>
      
      <p class="navbar-text pull-left">
        <%= link_to "View All Products", guests_products_path, :class => 'navbar-link'  %>
      </p>
      <p class="navbar-text pull-right">
        Viewing as Guest. |
        <%= link_to "End Session", root_path %>
      </p>
    </nav>
    
    <!--%= stylesheet_link_tag    'style', 'data-turbolinks-track': 'reload' %>-->

    <h1 align="right"><u>Meat</u></h1>
    
    <br>
    <br>
    <br>
    
    <table class="table table-striped">
        <thead>
            <th style="text-align: center">#</th>
            <th style="text-align: center">Product Name</th>
            <th>Price</th>
        </thead>
        <tbody>
            <% @products.each do |this_product| %>
            <tr>
                <td style="text-align: center">
                    <%= @products.index(this_product) + 1 %>
                </td>
                <td style="text-align: center">
                    <%= this_product.name %>
                </td>
                <td>
                    <%= "%.2f" % this_product.price %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
    
    <%= link_to 'Back', home_index_path, class: "btn btn-warning buttonBack" %>
  </body>
</html>

app/views/guests/produce.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MIS21 POS System</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'style', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <style>
      body{
      	height:100%;
      	width:100%;
      	margin: 0 0 0 0;
      	padding:20px 10px 10px 10px;
      	font-family: "Century Gothic";
      	background-image: url(http://cdn.wonderfulengineering.com/wp-content/uploads/2013/12/metal-wallpapers-2.jpg);
      	color: white;
      }
      
      div{
      	height:100%;
      	font-family: "Century Gothic";
      	color: white;
      }
      
      h1{
      	font-size: 7em;
      	color: white;
      }
      
      u{
      	border-bottom: 3px solid white;
      	text-decoration: none;
      	padding: 0 50px 10px;
      }
      
      .buttonBack{
          display: inline-block;
          border-radius: 10px;
          background-color: #B0C4DE;
          border: 3px solid #f2f2f2;
          color: black;
          text-align: center;
          font-size: 14px;
          padding: 10px;
          width: 100px;
          transition: all 0.5s;
          cursor: pointer;
          margin: 5px;
      }
    </style>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="navbar-header">
        <a class="navbar-brand" href="/guests/products"><strong>POS System</strong></a>
      </div>
      
      <p class="navbar-text pull-left">
        <%= link_to "View All Products", guests_products_path, :class => 'navbar-link'  %>
      </p>
      <p class="navbar-text pull-right">
        Viewing as Guest. |
        <%= link_to "End Session", root_path %>
      </p>
    </nav>
    
    <!--%= stylesheet_link_tag    'style', 'data-turbolinks-track': 'reload' %>-->

    <h1 align="right"><u>Produce</u></h1>
    
    <br>
    <br>
    <br>
    
    <table class="table table-striped">
        <thead>
            <th style="text-align: center">#</th>
            <th style="text-align: center">Product Name</th>
            <th>Price</th>
        </thead>
        <tbody>
            <% @products.each do |this_product| %>
            <tr>
                <td style="text-align: center">
                    <%= @products.index(this_product) + 1 %>
                </td>
                <td style="text-align: center">
                    <%= this_product.name %>
                </td>
                <td>
                    <%= "%.2f" % this_product.price %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
    
    <%= link_to 'Back', home_index_path, class: "btn btn-warning buttonBack" %>
  </body>
</html>

app/views/guests/products.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MIS21 POS System</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'style', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <style>
      body{
      	height:100%;
      	width:100%;
      	margin: 0 0 0 0;
      	padding:20px 10px 10px 10px;
      	font-family: "Century Gothic";
      	background-image: url(http://cdn.wonderfulengineering.com/wp-content/uploads/2013/12/metal-wallpapers-2.jpg);
      	color: white;
      }
      
      div{
      	height:100%;
      	font-family: "Century Gothic";
      	color: white;
      }
      
      h1{
      	font-size: 7em;
      	color: white;
      }
      
      u{
      	border-bottom: 3px solid white;
      	text-decoration: none;
      	padding: 0 50px 10px;
      }
      
      .buttonBack{
          display: inline-block;
          border-radius: 10px;
          background-color: #B0C4DE;
          border: 3px solid #f2f2f2;
          color: black;
          text-align: center;
          font-size: 14px;
          padding: 10px;
          width: 100px;
          transition: all 0.5s;
          cursor: pointer;
          margin: 5px;
      }
    </style>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="navbar-header">
        <a class="navbar-brand" href="/guests/products"><strong>POS System</strong></a>
      </div>
      
      <p class="navbar-text pull-left">
        <%= link_to "View Meat Products", guests_meat_path, :class => 'navbar-link'%> |
        <%= link_to "View Produce", guests_produce_path, :class => 'navbar-link'%> |
        <%= link_to "View Canned Goods", guests_cannedgoods_path, :class => 'navbar-link'%> |
        <%= link_to "View Sweets", guests_sweets_path, :class => 'navbar-link'%> |
        <%= link_to "View Hygiene Products", guests_hygiene_path, :class => 'navbar-link'%>
        
      </p>
      <p class="navbar-text pull-right">
        <i>Viewing as Guest</i>. |
        <%= link_to "End Session", root_path, :class => 'navbar-link' %>
      </p>
    </nav>
    
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    
    <!--%= stylesheet_link_tag    'style', 'data-turbolinks-track': 'reload' %>-->

    <h1 align="right"><u>Products</u></h1>
    
    <br>
    
    <br>
    <br>
    
    <table class="table table-striped">
        <thead>
            <th style="text-align: center">#</th>
            <th style="text-align: center">Product Name</th>
            <th>Availability</th>
            <th>Price</th>
            <!--<th colspan="3"></th>-->
        </thead>
        <tbody>
            <% @products.each do |this_product| %>
            <tr>
                <td style="text-align: center">
                    <%= @products.index(this_product) + 1 %>
                </td>
                <td style="text-align: center">
                    <%= this_product.name %>
                </td>
                <td>
                    <%= if this_product.status then "Available" else "Unavailable" end %>
                </td>
                <td>
                    <%= "%.2f" % this_product.price %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
    
    <%= link_to 'Back', home_index_path, class: "btn btn-warning buttonBack" %>

    <%= yield %>
  </body>
</html>

app/views/guests/show.html.erb
<%= stylesheet_link_tag    'style', 'data-turbolinks-track': 'reload' %>

<h1 align="right"><u>Products</u></h1>

<br>
<br>

<a href="/products/new"><button class="button1" style="vertical-align:middle"><span>Add New Products</span></button></a>

<br>
<br>

<table class="table table-striped">
    <thead>
        <th>Product Name</th>
        <th>Price</th>
        <th>Admin</th>
        <th>Status</th>
        <th colspan="3"></th>
    </thead>
    <tbody>
        <% @products.each do |this_product| %>
        <tr>
                <td>
                    <%= this_product.name %>
                </td>
                <td>
                    <%= "%.2f" % this_product.price %>
                </td>
                <td>
                    <%= if this_product.admin then this_product.admin.email else "NA" end %>
                </td>
                <td>
                    <%= if this_product.status then "Active" else "Inactive" end %>

                </td>
                <td>
                    <%= if this_product.status then link_to "Deactivate", product_path(this_product, this_product: {status: true}), 
                    method: :delete, class: "btn btn-danger" else link_to "Activate", product_path(this_product, this_product: {status: false}), 
                    method: :delete, class: "btn btn-primary" end %>
                </td>
                <td>
                     <%= link_to "Edit",
                        edit_product_path(this_product), class: "btn btn-warning" %>
                </td>
                <td>
                     <%= link_to "Show", product_path(this_product), class: "btn btn-success" %>
                </td>
        </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'Back', home_index_path, class: "btn btn-warning buttonBack" %>

app/views/guests/sweets.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MIS21 POS System</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'style', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <style>
      body{
      	height:100%;
      	width:100%;
      	margin: 0 0 0 0;
      	padding:20px 10px 10px 10px;
      	font-family: "Century Gothic";
      	background-image: url(http://cdn.wonderfulengineering.com/wp-content/uploads/2013/12/metal-wallpapers-2.jpg);
      	color: white;
      }
      
      div{
      	height:100%;
      	font-family: "Century Gothic";
      	color: white;
      }
      
      h1{
      	font-size: 7em;
      	color: white;
      }
      
      u{
      	border-bottom: 3px solid white;
      	text-decoration: none;
      	padding: 0 50px 10px;
      }
      
      .buttonBack{
          display: inline-block;
          border-radius: 10px;
          background-color: #B0C4DE;
          border: 3px solid #f2f2f2;
          color: black;
          text-align: center;
          font-size: 14px;
          padding: 10px;
          width: 100px;
          transition: all 0.5s;
          cursor: pointer;
          margin: 5px;
      }
    </style>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="navbar-header">
        <a class="navbar-brand" href="/guests/products"><strong>POS System</strong></a>
      </div>
      
      <p class="navbar-text pull-left">
        <%= link_to "View All Products", guests_products_path, :class => 'navbar-link'  %>
      </p>
      <p class="navbar-text pull-right">
        Viewing as Guest. |
        <%= link_to "End Session", root_path %>
      </p>
    </nav>
    
    <!--%= stylesheet_link_tag    'style', 'data-turbolinks-track': 'reload' %>-->

    <h1 align="right"><u>Sweets</u></h1>
    
    <br>
    <br>
    <br>
    
    <table class="table table-striped">
        <thead>
            <th style="text-align: center">#</th>
            <th style="text-align: center">Product Name</th>
            <th>Price</th>
        </thead>
        <tbody>
            <% @products.each do |this_product| %>
            <tr>
                <td style="text-align: center">
                    <%= @products.index(this_product) + 1 %>
                </td>
                <td style="text-align: center">
                    <%= this_product.name %>
                </td>
                <td>
                    <%= "%.2f" % this_product.price %>
                </td>
            </tr>
            <% end %>
        </tbody>
    </table>
    
    <%= link_to 'Back', home_index_path, class: "btn btn-warning buttonBack" %>
  </body>
</html>