config/routes.rb
Rails.application.routes.draw do

  # get 'daily_sales/index'

  # get 'order_lines/index'
  get 'orders/summary'
  get '/daily_sales' => 'orders#daily_sales', :as => :daily_sales
  get '/cashiers/ranking'
  get '/guests/products' => 'guests#products'
  get '/guests/meat' => 'guests#meat'
  get '/guests/produce' => 'guests#produce'
  get '/guests/cannedgoods' => 'guests#canned_goods'
  get '/guests/sweets' => 'guests#sweets'
  get '/guests/hygiene' => 'guests#hygiene'
  get 'cashiers/daily_sales' => 'cashiers#daily_sales'

  # get 'cashiers/index'

  devise_for :cashiers
  # , :controller => {:registrations => 'cashiers/registrations'}
  devise_for :admins
 
  root 'home#index'
  # devise_scope :admin do
  resources :home, :cashiers, :products, :orders, :order_lines, :daily_sales
  # map.orders '/daily_sales', :controller => 'order', :action => 'dailysales'
  # resources :orders go 
  #   get 'summary', :on => :collection
  # end
  # resources :orders, :path_prefix => ':cashiers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/cashier.rb
class Cashier < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
         
  # validate :password :on :update, allow_blank => true
  belongs_to :admin, :optional => true
  has_many :orders
  
  def active_for_authentication?
    super && status
  end
end

app/controllers/cashiers/registrations_controller.rb
class Cashiers::RegistrationsController < Devise::RegistrationsController
    
    # protected
    
    #     def update_resource(resource, params)
    #         resource.update_without_password(params)
    #     end



  # def inactive_message
  #   "d"
  # end
end

app/controllers/cashiers_controller.rb
class CashiersController < ApplicationController
  # before_action :authenticate_admin!
  before_action :set_cashier, only: [:update, :destroy, :edit, :show]
  
  def index
    @cashiers = Cashier.all
  end
  
  def new
    @cashier = Cashier.new
  end
  
  def create
    @cashier = Cashier.new(cashier_params)
    @cashier.admin = current_admin
    if @cashier.save
      redirect_to cashiers_path
    else
      render :new
    end
  end
  
   def destroy
    if @cashier.status
      @cashier.update({:status => false})
      # @cashier.status == false
    else
      @cashier.update({:status => true})
      # @cashier.status == true
    end
    redirect_to cashiers_path
   end
  
  def edit
  end
  
 def update
    if params[:cashier][:password].blank? && params[:cashier][:password_confirmation].blank?
      params[:cashier].delete(:password)
      params[:cashier].delete(:password_confirmation)
    end
    @cashier.update(cashier_params)
    redirect_to cashiers_path
  end
  
  def show
    @orders = @cashier.orders
  end
  
  def ranking
    @cashiers = Cashier.all
    @orders = Order.all
  end
  
  def daily_sales
    @orders = Order.all
  end
  
  private
    def cashier_params
      params.require(:cashier).permit!
    end
    
    def set_cashier
        @cashier = Cashier.find_by(id: params[:id])
        if !@cashier.present?
          redirect_to cashiers_path
        end
    end
    
    protected
        def sign_up(resource_name, resource)
            # sign_in(resource_name, resource)
        end
        
        def update_resource(resource, params)
            resource.update_without_password(params)
        end
        
        def update_needs_confirmation?(resource, previous)
        #resource.respond_to?(:pending_reconfirmation?) &&
        #resource.pending_reconfirmation? &&
        #previous != resource.unconfirmed_email
        end
end

app/helpers/cashiers_helper.rb
module CashiersHelper
end

app/views/cashiers/_form.html.erb
<%= form_for @cashier do |f| %>
    <label>Name</label>
    <%= f.text_field :name %><br>
    
    <label>Email</label>
    <%= f.email_field :email %><br>
    
    <label>Password</label>
    <%= f.password_field :password %><br>
    
    <%= f.submit %>
<% end %>

app/views/cashiers/daily_sales.html.erb
<%= stylesheet_link_tag    'style', 'data-turbolinks-track': 'reload' %>

<h1 align="right"><u>Daily Sales Report</u></h1>
<br>
<h4>As of <%= Date.today.to_s %></h4>

<% products = {} %>
<% sub = 0 %>
<% total = 0 %>

<% @orders.each do |order| %>
    <% if order.cashier == current_cashier %>
        <% order.order_lines.each do |o| %>
            <% if products.keys.include? (o.product.name.to_sym) %>
                <% prod = products[o.product.name.to_sym] %>
                <% products[o.product.name.to_sym] = 
                products[o.product.name.to_sym] + o.quantity %>
                
            <% else %>
                <% products[o.product.name.to_sym] = o.quantity %>
            <% end %>
        <% end %>
    <% end %>
<% end %>

<table class="table table-striped">
    <thead>
        <th>Product Name</th>
        <th>Quantity Sold</th>
        <th>Subtotal (VAT included)</th>
    </thead>
    <tbody>
        <% p = products.keys %>
        <% pr = products.values %>
        <% p.each do |prod| %>
            <tr>
                <td>
                    <%= prod.to_s %>
                </td>
                <td>
                    <%= products[prod.to_sym] %>
                </td>
                <td>
                    <% m = Product.where(:name => prod.to_s).first %>
                    <%= '%.2f' % st = (m.price * 1.12) * products[prod.to_sym] %>
                    <% total = total + st %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

<h3>Total Sales: <b><%= '%.2f' % total %></b></h3>
<br>
<br>

<%= link_to 'Back', home_index_path, class: "btn btn-warning buttonBack" %>

app/views/cashiers/edit.html.erb
<%= stylesheet_link_tag    'style', 'data-turbolinks-track': 'reload' %>

<h2><u>Edit Cashier</u></h2>
<br>
<br>

<%= form_for @cashier do |f| %>
    <label>Name</label>
    <div class="actions"><%= f.text_field :name %></div><br>
    
    <label>Email</label>
    <div class="actions"><%= f.email_field :email %></div><br>
    
    <label>Password</label>
    <div class="actions"><%= f.password_field :password %></div><br>
    
    <label>Password Confirmation</label>
    <div class="actions"><%= f.password_field :password_confirmation %></div><br>
    
    <div class="actions"><%= f.submit %></div>
<% end %>
<br>
<br>
<%= link_to 'Back', cashiers_path, class: "btn btn-warning buttonBack" %>

app/views/cashiers/index.html.erb
<%= stylesheet_link_tag    'style', 'data-turbolinks-track': 'reload' %>

<h1 align="right"><u>Cashiers</u></h1>

<br>
<br>

<a href="/cashiers/new"><button class="button1" style="vertical-align:middle"><span>Add New Cashier</span></button></a>
<a href="/cashiers/ranking"><button class="button1" style="vertical-align: middle"><span>View Ranking</span></button></a>

<br>
<br>

<table class="table table-striped">
    <thead>
        <th>Cashier Name</th>
        <th>Cashier E-mail</th>
        <th>Admin</th>
        <th>Status</th>
        <th colspan="3"></th>
    </thead>
    <tbody>
        <% @cashiers.each do |this_cashier| %>
            <tr>
                <td>
                    <%= this_cashier.name %>
                </td>
                <td>
                    <%= this_cashier.email %>
                </td>
                <td>
                    <%= if this_cashier.admin then this_cashier.admin.email else "NA" end %>
                </td>
                <td>
                    <%= if this_cashier.status then "Active" else "Inactive" end %>
                </td>
                <td>
                    <%= if this_cashier.status then link_to "Deactivate", cashier_path(this_cashier, this_cashier: {status: true}), 
                    method: :delete, class: "btn btn-danger" else link_to "Activate", cashier_path(this_cashier, this_cashier: {status: false}), 
                    method: :delete, class: "btn btn-primary" end %>
                </td>
                <td>
                    <%= link_to "Edit", edit_cashier_path(this_cashier), class: "btn btn-warning" %>
                </td>
                <td>
                     <%= link_to "Show", cashier_path(this_cashier), class: "btn btn-success" %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>

<%= link_to 'Back', home_index_path, class: "btn btn-warning buttonBack" %>

app/views/cashiers/new.html.erb
<%= stylesheet_link_tag    'style', 'data-turbolinks-track': 'reload' %>

<h2><u>New Cashier</u></h2>
<br>
<br>
<%= form_for @cashier do |f| %>
    <label>Name</label>
    <div class="actions"><%= f.text_field :name %></div><br>
    
    <label>Email</label>
    <div class="actions"><%= f.email_field :email %></div><br>
    
    <label>Password</label>
    <div class="actions"><%= f.password_field :password %></div><br>
    
    <label>Password Confirmation</label>
    <div class="actions"><%= f.password_field :password_confirmation %></div><br>
    
    <div class="actions"><%= f.submit %></div>
<% end %>
<br>
<br>
<%= link_to 'Back', url_for(:back), class: "btn btn-warning buttonBack" %>

app/views/cashiers/ranking.html.erb
<%= stylesheet_link_tag    'style', 'data-turbolinks-track': 'reload' %>

<h2 align="center">♕ Cashier Ranking ♕</h2>
<h3 align="center"><u>based on sales</u></h3>
<br>
<br>


<!--tr>-->
<!--<td>-->
<!--   %= order.id %>-->
<!--</td>-->
<!--<td>-->
<!--    %= order.created_at %>-->
<!--</td>-->
<!--<td>-->
<!--    %= order.total_price %>-->
<!--</td>-->
<!--</tr>-->

<% a = {} %>
<% @cashiers.each do |hmmm| %>
    <% if a.keys.include? (hmmm.name.to_sym) %>
    <% else %>
        <% a[hmmm.name.to_sym] = 0 %>
    <% end %>
<% end %>
<% cashiertotal = nil %>

<% shhh = a.keys %>

<% shhh.each do |ayyy| %>
    <% @orders.each do |order| %>
        <% if order.cashier.name == ayyy.to_s %>
            <% a[ayyy] = a[ayyy] +  order.total_price %>
        <% end %>
    <% end %>
<% end %>
<% c = a.sort {|a,b| a[1]<=>b[1]}.reverse %>
<% d = [] %>
<% c.each do |a,b| %>
    <% d << a %>
<% end %>

<table class="table table-striped">
    <thead>
        <th>
            Rank
        </th>
        <th>
            Name
        </th>
        <th>
            $$$ Made
        </th>
    </thead>
    <tbody>
        <% d.each do |this| %>
        <tr>
            <td>
                <%= d.index(this) + 1 %>
            </td>
            <td>
                <%= this.to_s %>
            </td>
            <td>
                <%= a[this] %>
            </td>
        </tr>
        <% end %>
    </tbody>
</table>

<br>
<br>

<%= link_to 'Back', url_for(:back), class: "btn btn-warning buttonBack" %>

app/views/cashiers/show.html.erb
<%= stylesheet_link_tag    'style', 'data-turbolinks-track': 'reload' %>

<h2><u>Cashier #<%= @cashier.id%></u></h2>
<br>
<h3>Name: <%= @cashier.name %></h3>
<h3>Status: <%= if @cashier.status then "Active" else "Inactive" end %></h3>
<br>

<% cashiertotal = nil %>
<table class="table table-striped">
    <thead>
        <th>Order ID</th>
        <th>Order Date</th>
        <th>Total Price</th>
        <th>            </th>
    </thead>
    <tbody>
        <% @orders.each do |order| %>
        <tr>
            <% if order.cashier == @cashier %>
            <td>
               <%= order.id %>
            </td>
            <td>
                <%= order.created_at %>
            </td>
            <td>
                <%= order.new_total_price %>
            </td>
            <td>
                <!--%= link_to "Show", cashier_path(this_cashier), class: "btn btn-success" %>-->
                <%= link_to "Show", order_path(order), class: "btn btn-success" %>
            </td>
            
                <% if cashiertotal == nil %>
                    <% cashiertotal = 0 %>
                    <% cashiertotal = cashiertotal +  order.new_total_price %>
                <% else %>
                    <% cashiertotal = cashiertotal +  order.new_total_price %>
                <% end %>
                <% end %>
        <% end %>
        </tr>
    </tbody>
</table>
<h3>Cashier's Total: <b><%= cashiertotal %></b> </h3><br>
<br>
<br>

<%= link_to 'Back', cashiers_path, class: "btn btn-warning buttonBack" %>