config/routes.rb
Rails.application.routes.draw do

  # get 'daily_sales/index'

  # get 'order_lines/index'
  get 'orders/summary'
  get '/daily_sales' => 'orders#daily_sales', :as => :daily_sales
  get '/cashiers/ranking'
  get '/guests/products' => 'guests#products'
  get '/guests/meat' => 'guests#meat'
  get '/guests/produce' => 'guests#produce'
  get '/guests/cannedgoods' => 'guests#canned_goods'
  get '/guests/sweets' => 'guests#sweets'
  get '/guests/hygiene' => 'guests#hygiene'
  get 'cashiers/daily_sales' => 'cashiers#daily_sales'

  # get 'cashiers/index'

  devise_for :cashiers
  # , :controller => {:registrations => 'cashiers/registrations'}
  devise_for :admins
 
  root 'home#index'
  # devise_scope :admin do
  resources :home, :cashiers, :products, :orders, :order_lines, :daily_sales
  # map.orders '/daily_sales', :controller => 'order', :action => 'dailysales'
  # resources :orders go 
  #   get 'summary', :on => :collection
  # end
  # resources :orders, :path_prefix => ':cashiers'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MIS21 POS System</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'style' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="navbar-header">
        <a class="navbar-brand" href="/home"><strong>POS System</strong></a>
      </div>
      
      <p class="navbar-text pull-left">
        <% if admin_signed_in? %>
          <%= link_to 'View Products', products_path, :class => 'navbar-link' %> |
          <%= link_to "View Cashiers", cashiers_path,  :class => 'navbar-link'  %> |
          <%= link_to "View Reports", daily_sales_path, :class => 'navbar-link'  %>
        <% else %>
          <% if cashier_signed_in? %>
            <%= link_to "View Orders", orders_path, :class => 'navbar-link'  %> | 
            <%= link_to "View Reports", cashiers_daily_sales_path, :class => 'navbar-link' %>
          <% end %>
        <% end %>
      </p>
      <p class="navbar-text pull-right">
        <% if admin_signed_in? %>
          Logged in as <strong><%= current_admin.email%></strong>.
          <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <% if cashier_signed_in? %>
            Logged in as <strong><%= current_cashier.email%></strong>.
            <!--%= link_to 'Edit profile', edit_cashie_path, :class => 'navbar-link' %> |-->
            <%= link_to "Logout", destroy_cashier_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <!--%= link_to "Login as Admin", new_admin_session_path, :class => 'navbar-link'  %> |-->
            <!--%= link_to "Login as Cashier", new_cashier_session_path, :class => 'navbar-link'  %> |-->
            <!--%= link_to "View as Customer", guests_products_path, :class => 'navbar-link'  %>-->
          <% end %>
        <% end %>
      </p>
    </nav>
    
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MIS21 POS System</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'style' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-inverse">
      <div class="navbar-header">
        <a class="navbar-brand" href="/home"><strong>POS System</strong></a>
      </div>
      
      <p class="navbar-text pull-left">
        <% if admin_signed_in? %>
          <%= link_to 'View Products', products_path, :class => 'navbar-link' %> |
          <%= link_to "View Cashiers", cashiers_path,  :class => 'navbar-link'  %> |
          <%= link_to "View Reports", daily_sales_path, :class => 'navbar-link'  %>
        <% else %>
          <% if cashier_signed_in? %>
            <%= link_to "View Orders", orders_path, :class => 'navbar-link'  %> | 
            <%= link_to "View Reports", cashiers_daily_sales_path, :class => 'navbar-link' %>
          <% end %>
        <% end %>
      </p>
      <p class="navbar-text pull-right">
        <% if admin_signed_in? %>
          Logged in as <strong><%= current_admin.email%></strong>.
          <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
        <% else %>
          <% if cashier_signed_in? %>
            Logged in as <strong><%= current_cashier.email%></strong>.
            <!--%= link_to 'Edit profile', edit_cashie_path, :class => 'navbar-link' %> |-->
            <%= link_to "Logout", destroy_cashier_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Login as Admin", new_admin_session_path, :class => 'navbar-link'  %> |
            <%= link_to "Login as Cashier", new_cashier_session_path, :class => 'navbar-link'  %> |
            <%= link_to "View as Customer", guests_products_path, :class => 'navbar-link'  %>
          <% end %>
        <% end %>
      </p>
    </nav>
    
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>